FROM golang:1.23.4-alpine3.21 as build
WORKDIR /build
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine:3.21.0 as app
WORKDIR /app
COPY --from=build /build/main .
CMD [ "./main" ]