#Autor: Fagner Geraldes Braga
#Data de criação: 30/12/2024
#Data de atualização: 30/12/2024
#Versão: 0.01

#FROM (Create a new build stage from a base image)
FROM baseImage

#LABEL (Add metadata to an image)
LABEL author="Fagner Geraldes Braga"
LABEL contact="fagner.fgb@gmail.com"
LABEL description="Curl installation"
LABEL source="https://github.com/fagnerfgb/devops"
LABEL documentation="https://github.com/fagnerfgb/devops/blob/master/04-docker.md"

#RUN (Execute build commands)


#WORKDIR (Change working directory)
WORKDIR /app

#COPY: (Copy files and directories)


#ENTRYPOINT (Specify default executable.)
ENTRYPOINT [ "" ]

#CMD (Specify default commands)
CMD [ "" ]

#USER (Set user and group ID)


#EXPOSE (Describe which ports your application is listening on)
EXPOSE 80

#ARG (Use build-time variables)
ARG VAR_TEXTO="Texto XPTO"

#VOLUME (Create volume mounts)
VOLUME /app

#ENV (Set environment variables)
ENV VALOR_DOCKER_ENV="Valor XPTO"

#ADD (Copy files/directories into a Docker image. It can copy data in three ways:
#1- Copy files from the local storage to a destination in the Docker image.
#2- Copy a tarball from the local storage and extract it automatically inside a destination in the Docker image.
#3- Copy files from a URL to a destination inside the Docker image.