services:
  # Serviço 'web' definido no arquivo de composição Docker
  web:
    # Especifica a imagem Docker a ser usada para o serviço
    image: fagnerfgb/caos:v1
    # Mapeia a porta 8080 do host para a porta 3000 do container
    ports:
    - 8080:3000
    # Configura a política de reinício para o serviço
    # restart: on-failure      # Reinicia o container somente em caso de falhas (desativado)
    # restart: unless-stopped  # Reinicia automaticamente o container, exceto se ele foi parado manualmente (desativado)
    restart: always # Reinicia o container sempre, independentemente da causa (ativa)
    # Configuração de verificação de saúde do container
    healthcheck:
      # Comando a ser executado para verificar a saúde do container
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      # Intervalo entre as verificações de saúde
      interval: 30s
      # Tempo limite para o comando de verificação de saúde
      timeout: 5s
      # Número de tentativas antes de marcar o container como unhealthy
      retries: 2
      # Período de espera antes de iniciar as verificações de saúde
      start_period: 30s
