#Autor: Fagner Geraldes Braga
#Data de criação: 30/12/2024
#Data de atualização: 30/12/2024
#Versão: 0.01

#FROM (Create a new build stage from a base image)
FROM node:23.5.0-alpine3.20

#EXPOSE (Describe which ports your application is listening on)
EXPOSE 8080

#LABEL (Add metadata to an image)
LABEL author="Fagner Geraldes Braga"
LABEL contact="fagner.fgb@gmail.com"
LABEL description="App Conversão de Temeperatura em NodeJS"
LABEL source="https://github.com/fagnerfgb/devops"
LABEL documentation="https://github.com/fagnerfgb/devops/blob/master/04-docker.md"

#WORKDIR (Change working directory)
WORKDIR /app

#COPY: (Copy files and directories)
COPY package*.json .

#RUN (Execute build commands)
RUN npm install

#COPY: (Copy files and directories)
COPY . .

#ENTRYPOINT (Specify default executable.)
ENTRYPOINT [ "node", "server.js" ]