services:
  # Serviço Postgres
  postgre:
    # Nome do container
    container_name: fgb-postgre
    
    # Imagem Docker do Postgres
    image: postgres:12.17
    
    # Porta 5432 do host mapeada para a porta 5432 do container
    ports:
      - 5432:5432
    
    # Variáveis de ambiente para configuração do banco de dados
    environment:
      POSTGRES_PASSWORD: pwdkubenews  # Senha do usuário do banco
      POSTGRES_USER: kubenews         # Nome do usuário
      POSTGRES_DB: kubenews           # Nome do banco de dados
    
    # Volume para persistência de dados
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data
    
    # Rede personalizada para o serviço
    networks:
      - kube_news_net

  # Serviço da aplicação kube-news
  kube_news:
    # Imagem Docker da aplicação kube-news
    image: fagnerfgb/kube-news:v1
    
    # Porta 8080 do host mapeada para a porta 8080 do container
    ports:
      - 8080:8080
    
    # Rede personalizada para o serviço
    networks:
      - kube_news_net
    
    # Variáveis de ambiente para configuração do banco de dados
    environment:
      DB_DATABASE: kubenews      # Nome do banco de dados
      DB_USERNAME: kubenews      # Nome do usuário do banco de dados
      DB_PASSWORD: pwdkubenews   # Senha do banco de dados
      DB_HOST: fgb-postgre       # Nome do container do Postgres (que será usado para conexão)

# Definição do volume
volumes:
  postgre_docker_vol:
    # Nome do volume gerenciado pelo Docker
    name: my_postgre_vol

# Definição da rede personalizada
networks:
  kube_news_net:
    # Nome da rede no Docker
    name: knews_network
    
    # Driver de rede utilizado (bridge)
    driver: bridge