services:
  # Serviço Postgres
  postgre:
    # Nome do container
    container_name: fgb-postgre
    # Imagem Docker do Postgres
    image: postgres:12.17
    # Porta 5432 do host mapeada para a porta 5432 do container
    ports:
      - 5432:5432
    # Variáveis de ambiente
    environment:
      POSTGRES_PASSWORD: pwdkubenews
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data
    networks:
      - kube_news_net    
  kube_news:
    image: fagnerfgb/kube-news:v2
    ports:
      - 8080:8080
    networks:
      - kube_news_net
    environment:
      - DB_DATABASE: kubenews 
      - DB_USERNAME: kubenews 
      - DB_PASSWORD: pwdkubenews 
      - DB_HOST: fgb-postgre
volumes:
  postgre_docker_vol:
    name: my_postgre_vol
networks:
  kube_news_net:
    name: knews_network
    driver: bridge