#Autor: Fagner Geraldes Braga
#Data de criação: 30/12/2024
#Data de atualização: 30/12/2024
#Versão: 0.01

## Desafio 03 - Banco de Dados MongoDB

#Pra finalizar essa etapa, crie o comando pra criar o banco de dados MongoDB usando os requisitos abaixo:

    # O usuário root do banco deve ser mongo_usr
    # A senha do usuário root deve ser mongo_pwd

# Lembrando que a execução em container deve ser transparente pra quem está desenvolvendo. 
# E que aqui você não precisa se preocupar com a perda dos dados do banco e nem nada disso, 
# é apenas para desenvolvimento pontual.

#FROM (Create a new build stage from a base image)
FROM mongo

#EXPOSE (Describe which ports your application is listening on)
EXPOSE 27017

#LABEL (Add metadata to an image)
LABEL author="Fagner Geraldes Braga"
LABEL contact="fagner.fgb@gmail.com"
LABEL description="MongoDB Database"
LABEL source="https://github.com/fagnerfgb/devops"
LABEL documentation="https://github.com/fagnerfgb/devops/blob/master/docker/desafios/desafio3.md"

#ENV (Set environment variables)
ENV MONGO_INITDB_ROOT_USERNAME=mongo_usr
ENV MONGO_INITDB_ROOT_PASSWORD=mongo_pwd

ENTRYPOINT [ "executable" ]