#Autor: Fagner Geraldes Braga
#Data de criação: 30/12/2024
#Data de atualização: 30/12/2024
#Versão: 0.01

# Desafio 01 - Banco de Dados Postgresql

# Você está dando os primeiros passos no uso de containers.
# E a melhor forma de iniciar no mundo de containers é usar em ambiente de desenvolvimento.
# Sua missão é ajudar a equipe de desenvolvimento a ter mais autonomia no desenvolvimento de projetos. 
# E uma das reclamações da equipe é o setup local.
# Crie um comando para criar um banco de dados PostgreSQL no ambiente do desenvolvedor 
# de uma forma que cumpra os seguintes requisitos:

    # O nome do banco de dados deve ser curso_docker
    # O usuário de acesso ao banco deve ser docker_usr
    # A senha do usuário deve ser docker_pwd

#Lembrando que a execução em container deve ser transparente pra quem está desenvolvendo. 
# E que aqui você não precisa se preocupar com a perda dos dados do banco e nem nada disso, 
# é apenas para desenvolvimento pontual.

#FROM (Create a new build stage from a base image)
FROM postgres

#EXPOSE (Describe which ports your application is listening on)
EXPOSE 5432

#LABEL (Add metadata to an image)
LABEL author="Fagner Geraldes Braga"
LABEL contact="fagner.fgb@gmail.com"
LABEL description="PostgreSQL Database"
LABEL source="https://github.com/fagnerfgb/devops"
LABEL documentation="https://github.com/fagnerfgb/devops/blob/master/docker/desafios/desafio1.md"

#ENV (Set environment variables)
ENV POSTGRES_PASSWORD="docker_pwd"
ENV POSTGRES_USER=docker_usr
ENV POSTGRES_DB=curso_docker