#Autor: Fagner Geraldes Braga
#Data de criação: 31/12/2024
#Data de atualização: 31/12/2024
#Versão: 0.01

#FROM (Create a new build stage from a base image)
FROM ubuntu:22.04

#LABEL (Add metadata to an image)
LABEL author="Fagner Geraldes Braga"
LABEL contact="fagner.fgb@gmail.com"
LABEL description="Docker Volume"
LABEL source="https://github.com/fagnerfgb/devops"
LABEL documentation="https://github.com/fagnerfgb/devops/blob/master/04-docker.md"

#WORKDIR (Change working directory)
WORKDIR /app

#VOLUME (Create volume mounts)
VOLUME /app